### ISSUE TITLE
IE11: Invalid Calling Object

### ISSUE THREAD

**Issue by mattdell** [defunctzombie/node-process#63] opened 2016-07-04 17:53 UTC
I'm having an issue on IE11 when calling process I get the error "Invalid Calling Object" in the method `process.nextTick()`.

![screen shot 2016-07-04 at 18 02 49](https://cloud.githubusercontent.com/assets/2536442/16566988/8d88221e-4211-11e6-8ef5-cc9f8abac63c.png)

Would anyone be able to shed some light on this one? It's extremely difficult to debug in IE, but `cachedSetTimeout` and `drainQueue` are both defined.

I'm guessing it might be related to this? https://msdn.microsoft.com/en-us/library/gg622930(v=vs.85).aspx

**Comment by calvinmetcalf** [comment] 2016-07-05 12:17
are you perhaps running with a bundler that is using eval to run it ?

**Comment by calvinmetcalf** [comment] 2016-07-05 12:34
dupe of #62 which we tracked down to a weird interaction between the webpack dev build and ie, I'm investigating fixes

**Comment by calvinmetcalf** [comment] 2016-07-05 12:37
we can talk about this in #62

**Closed by calvinmetcalf** 2016-07-05 12:37 UTC

**Comment by mattdell** [comment] 2016-07-05 12:57
Yeah, just like in #62 removing `devtool: 'cheap-module-eval-source-map'` fixes my issue.
